/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Shell */

#ifndef _Included_Shell
#define _Included_Shell
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Shell
 * Method:    changeDirectory
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Shell_changeDirectory
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
